/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package tarea.calculadoraprincipal;

import javax.swing.JOptionPane;

/**
 *
 * @author david
 * @matricula 2023-0243
 */
public class CalculadoraGUI extends javax.swing.JFrame {

    /**
     * Creates new form CalculadoraGUI
     */
    public CalculadoraGUI() {
        initComponents();
        this.setLocation(683, 384);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanTitulo = new javax.swing.JPanel();
        LbTitulo = new javax.swing.JLabel();
        LbIcon = new javax.swing.JLabel();
        panelValores = new javax.swing.JPanel();
        LBvalor1 = new javax.swing.JLabel();
        TexValor1 = new javax.swing.JTextField();
        LBvalor2 = new javax.swing.JLabel();
        TexValor2 = new javax.swing.JTextField();
        LBvalor3 = new javax.swing.JLabel();
        TexValor3 = new javax.swing.JTextField();
        PanelOperaciones = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        PanTitulo.setBackground(new java.awt.Color(153, 153, 153));
        PanTitulo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        LbTitulo.setFont(new java.awt.Font("Consolas", 1, 24)); // NOI18N
        LbTitulo.setForeground(new java.awt.Color(0, 0, 0));
        LbTitulo.setText("Calculadora Basica");
        PanTitulo.add(LbTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(125, 34, -1, -1));

        LbIcon.setIcon(new javax.swing.ImageIcon("C:\\Users\\david\\OneDrive\\Escritorio\\MATERIAS_DE_ ITLA\\Cuarto_Cuatrimestre\\PROGRAMACION 1\\Programas\\PROGRAMA 4\\Calculadoraprincipal\\src\\main\\java\\tarea\\calculadoraprincipal\\imagenes\\calculator.png")); // NOI18N
        PanTitulo.add(LbIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 30, -1, 20));

        getContentPane().add(PanTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 480, 100));

        panelValores.setBackground(new java.awt.Color(204, 204, 255));
        panelValores.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        LBvalor1.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
        LBvalor1.setForeground(new java.awt.Color(0, 0, 0));
        LBvalor1.setText("Valor 1");
        LBvalor1.setToolTipText("");
        panelValores.add(LBvalor1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        TexValor1.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        TexValor1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        TexValor1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TexValor1ActionPerformed(evt);
            }
        });
        TexValor1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TexValor1KeyTyped(evt);
            }
        });
        panelValores.add(TexValor1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 10, 110, 30));

        LBvalor2.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
        LBvalor2.setForeground(new java.awt.Color(0, 0, 0));
        LBvalor2.setText("Valor 2");
        LBvalor2.setToolTipText("");
        panelValores.add(LBvalor2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, -1, -1));

        TexValor2.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        TexValor2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        TexValor2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TexValor2ActionPerformed(evt);
            }
        });
        TexValor2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TexValor2KeyTyped(evt);
            }
        });
        panelValores.add(TexValor2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 60, 110, 30));

        LBvalor3.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
        LBvalor3.setForeground(new java.awt.Color(0, 0, 0));
        LBvalor3.setText("Resultado");
        LBvalor3.setToolTipText("");
        panelValores.add(LBvalor3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 110, -1, -1));

        TexValor3.setEditable(false);
        TexValor3.setFont(new java.awt.Font("Consolas", 1, 24)); // NOI18N
        TexValor3.setForeground(new java.awt.Color(0, 0, 0));
        TexValor3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        TexValor3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TexValor3ActionPerformed(evt);
            }
        });
        TexValor3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TexValor3KeyTyped(evt);
            }
        });
        panelValores.add(TexValor3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 140, 140, 50));

        getContentPane().add(panelValores, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 240, 200));

        PanelOperaciones.setBackground(new java.awt.Color(204, 204, 204));
        PanelOperaciones.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        PanelOperaciones.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setText("Sumar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        PanelOperaciones.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 70, 30));

        jButton2.setText("Restar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        PanelOperaciones.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 30, 70, 30));

        jButton3.setText("Multiplicar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        PanelOperaciones.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 70, 30));

        jButton4.setText("Dividir");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        PanelOperaciones.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 90, 70, 30));

        jButton5.setText("Limpiar");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        PanelOperaciones.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 150, 90, 30));

        getContentPane().add(PanelOperaciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 100, 240, 200));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TexValor1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TexValor1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TexValor1ActionPerformed

    private void TexValor2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TexValor2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TexValor2ActionPerformed

    private void TexValor3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TexValor3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TexValor3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        validarCampos();
        restarValores();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void TexValor1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TexValor1KeyTyped
        char numeros = evt.getKeyChar();
        if ((numeros < '0' || numeros > '9') && (numeros < ',' || numeros > '.')) {
            JOptionPane.showMessageDialog(null, "Favor ingresar numeros para realizar la operacion.");
            evt.consume();
        }
    }//GEN-LAST:event_TexValor1KeyTyped

    private void TexValor2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TexValor2KeyTyped
        char numeros = evt.getKeyChar();
        if ((numeros < '0' || numeros > '9') && (numeros < ',' || numeros > '.')) {
            JOptionPane.showMessageDialog(null, "Favor ingresar numeros para realizar la operacion.");
            evt.consume();
        }
    }//GEN-LAST:event_TexValor2KeyTyped

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        validarCampos();
        sumarValores();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        limpiarCampos();
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        validarCampos();
        multiplicarValores();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        validarCampos();
        divicionValores();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void TexValor3KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TexValor3KeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_TexValor3KeyTyped
    private void validarCampos() {
        if (TexValor1.getText().trim().length() <= 0) {
            JOptionPane.showMessageDialog(null, "Favor ingresar valor 1, el campo esta vacio.");
            TexValor1.requestFocus();
        } else if (TexValor2.getText().trim().length() <= 0) {
            JOptionPane.showMessageDialog(null, "Favor ingresar valor , el campo esta vacio.");
            TexValor1.requestFocus();
        }
    }

    private void sumarValores() {
        Calculadora cal = new Calculadora();
        double respuesta = cal.sumar(Double.parseDouble(TexValor1.getText()), Double.parseDouble(TexValor2.getText()));
        TexValor3.setText(respuesta + "");
    }

    private void restarValores() {
        Calculadora Cal = new Calculadora();
        double respuesta = Cal.restar(Double.parseDouble(TexValor1.getText()), Double.parseDouble(TexValor2.getText()));
        TexValor3.setText(respuesta + "");
    }

    private void multiplicarValores() {
        Calculadora Cal = new Calculadora();
        double respuesta = Cal.multiplicar(Double.parseDouble(TexValor1.getText()), Double.parseDouble(TexValor2.getText()));
        TexValor3.setText(respuesta + "");
    }

    private void divicionValores() {
        Calculadora Cal = new Calculadora();
        double respuesta = Cal.dividir(Double.parseDouble(TexValor1.getText()), Double.parseDouble(TexValor2.getText()));
        TexValor3.setText(respuesta + "");
    }

    private void limpiarCampos() {
        TexValor1.setText("");
        TexValor2.setText("");
        TexValor3.setText("");
        TexValor1.requestFocus();
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CalculadoraGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CalculadoraGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CalculadoraGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CalculadoraGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new CalculadoraGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LBvalor1;
    private javax.swing.JLabel LBvalor2;
    private javax.swing.JLabel LBvalor3;
    private javax.swing.JLabel LbIcon;
    private javax.swing.JLabel LbTitulo;
    private javax.swing.JPanel PanTitulo;
    private javax.swing.JPanel PanelOperaciones;
    private javax.swing.JTextField TexValor1;
    private javax.swing.JTextField TexValor2;
    private javax.swing.JTextField TexValor3;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JPanel panelValores;
    // End of variables declaration//GEN-END:variables
}
